### ISSUE TITLE
help I can't compile

### ISSUE THREAD

**Issue by technopal** [Nedemai/PicoPak64#1]
I already tried to compile it, with Visual Studio code, but it gives me this error:
```

PS C:\Users\UsX\Documents\Pico-v1.5.1\pico-examples\PicoPak64\build> cmake ..
-- Building for: Ninja
CMake Error at CMakeLists.txt:4 (family_get_project_name):
   Unknown CMake command "family_get_project_name".


CMake Warning (dev) in CMakeLists.txt:
   No cmake_minimum_required command is present. A line of code such as

     cmake_minimum_required(VERSION 3.25)
```

I can compile the pico sdk and tinyusb examples, but not this, could you help me or send me the uf2 file?

**Comment by Nedemai** [comment]
> I already tried to compile it, with Visual Studio code, but it gives me this error:
> 
> ```
> 
> PS C:\Users\UsX\Documents\Pico-v1.5.1\pico-examples\PicoPak64\build> cmake ..
> -- Building for: Ninja
> CMake Error at CMakeLists.txt:4 (family_get_project_name):
>    Unknown CMake command "family_get_project_name".
> 
> 
> CMake Warning (dev) in CMakeLists.txt:
>    No cmake_minimum_required command is present. A line of code such as
> 
>      cmake_minimum_required(VERSION 3.25)
> ```
> 
> I can compile the pico sdk and tinyusb examples, but not this, could you help me or send me the uf2 file?

Sorry for the late reply, I uploaded the uf2 file to the repository today. There are some dependency issues that need to be resolved.
